FROM node:23.3.0-slim AS build-stage

WORKDIR /app

COPY ../frontend/package*.json ./
COPY ../frontend/ ./
COPY ../docker/nginx.conf ./

RUN npm install
RUN npm run build

FROM nginx:alpine AS runtime-stage

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY --from=build-stage /app/nginx.conf /etc/nginx/nginx.conf

