FROM python:3.12

WORKDIR /app

COPY ../backend/pyproject.toml ../backend/pdm.lock ./
RUN pip install pdm && pdm install

ENV PATH="/app/.venv/bin:${PATH}"

COPY ../backend/alembic /app/alembic
COPY ../backend/alembic.ini /app/alembic.ini
COPY ../backend/src /app/src

COPY ../backend/entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["pdm", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]