FROM node:23.3.0-slim

WORKDIR /app

COPY ../frontend/package*.json ./

RUN npm install

COPY ../frontend/ ./

RUN npm run build

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]