"""add cascade delete for token_pairs

Revision ID: 034b687f24e1
Revises: 6fabfbdea0d3
Create Date: 2025-04-19 14:26:40.314123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034b687f24e1'
down_revision: Union[str, None] = '6fabfbdea0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_pairs_user_id_fkey', 'token_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'token_pairs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_pairs', type_='foreignkey')
    op.create_foreign_key('token_pairs_user_id_fkey', 'token_pairs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
