"""Add must_change_password field for first admin user

Revision ID: dfb078753894
Revises: 0098d638edaf
Create Date: 2025-04-03 15:00:34.089711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfb078753894"
down_revision: Union[str, None] = "0098d638edaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    # ### end Alembic commands ###
