"""update dashboards and blocks

Revision ID: fa170f41fb74
Revises: 2a901b38d26c
Create Date: 2025-05-14 02:14:39.830222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa170f41fb74'
down_revision: Union[str, None] = '2a901b38d26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_blocks', sa.Column('container_id', sa.String(), nullable=True))
    op.add_column('dashboard_blocks', sa.Column('metric_type', sa.String(), nullable=True))
    op.add_column('dashboards', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('dashboards_title_key', 'dashboards', type_='unique')
    op.create_foreign_key(None, 'dashboards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.create_unique_constraint('dashboards_title_key', 'dashboards', ['title'])
    op.drop_column('dashboards', 'user_id')
    op.drop_column('dashboard_blocks', 'metric_type')
    op.drop_column('dashboard_blocks', 'container_id')
    # ### end Alembic commands ###
